### ISSUE TITLE
Uncaught SyntaxError: Invalid shorthand property initializer

### ISSUE THREAD

**Issue by abisee** [rohanchandra/type-theme#55] opened 2017-08-30 18:12 UTC
When I run
```
bundle exec jekyll serve
```
on this repo, I get a number of errors:

<img width="491" alt="screenshot 2017-08-30 11 10 51" src="https://user-images.githubusercontent.com/14880223/29887956-fc706aca-8d73-11e7-9808-fbdec6ddd832.png">

What's causing these errors and could they be causing other problems? I'm using the Type theme for my website and I'm having a number of problems that are hard to diagnose, and I'm not sure if this error is part of it.

**Comment by rohanchandra** [comment] 2017-08-31 07:37
Hi @abisee 

I've just fixed the first error (X-Frame-Options) in e3ffbb0f6c4e5d604cfbdd40c3846dedf4936752, as the tag is ignored in Chrome, however I can't reproduce the JavaScript errors.

Clicking the "VM16312:10" in the browser console will show you where the error is coming from.

Could you please send through the JavaScript code which comes up when you click on the error?

**Comment by abisee** [comment] 2017-08-31 21:09
Thanks @rohanchandra for fixing the `X-Frame-Options` error.

Actually, I'm no longer seeing the `Uncaught SyntaxError` when I serve this repo -- I'm not sure what I've changed about my environment but I must have updated something relevant.

**Comment by rohanchandra** [comment] 2017-09-03 11:00
No problem, I'll close this issue for now then.

**Closed as completed** 2017-09-03 11:00 UTC
